<<<<<<< HEAD
# Generated by Django 4.1 on 2022-08-29 14:29
=======
# Generated by Django 4.1 on 2022-08-30 18:55
>>>>>>> ramita

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('camada', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=33)),
                ('FechaDeEntrega', models.DateField()),
                ('Entregado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=33)),
                ('apellido', models.CharField(max_length=33)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=33)),
                ('apellido', models.CharField(max_length=33)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profesion', models.CharField(max_length=33)),
            ],
        ),
    ]
